### ISSUE TITLE
Test newer versions of Emacs

### ISSUE THREAD

**Issue by slackline** [ShuguangSun/tree-sitter-ess-r#8]
Emacs [29.1](https://www.gnu.org/software/emacs/news/NEWS.29.1) has been out for a while, it would be useful if the various CI/GitHub workflows tested against `29.1` as well as the current `27.2`.

Should be straight-forward to add `- 29.1` to the `emacs_version` matrix....

```yaml
      matrix:
        emacs_version:
          - 27.2
          - 29.1     
```
